import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Navbar from '@/components/Navbar';
import RegisterModal from '@/components/modals/RegisterModal';
import ToasterProvider from './providers/ToastProvider';
import { cn } from '@/lib/utils';
import LoginModal from '@/components/modals/LoginModal';
import getCurrentUser from './actions/getCurrentUser';
import UploadModal from '@/components/modals/UploadModal';
import Providers from '@/components/Providers';

import "react-loading-skeleton/dist/skeleton.css"

import 'simplebar-react/dist/simplebar.min.css';



const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const currentUser = await getCurrentUser();

  return (
    <html
      lang="en"
      className="light"
    >
      <Providers>
        <body
          className={cn(
            'min-h-screen font-sans antialiased grainy ',
            inter.className
          )}
        >
          <ToasterProvider />
          <RegisterModal />
          <LoginModal />
          <UploadModal />

          <Navbar currentUser={currentUser} />
          {children}
        </body>
      </Providers>
    </html>
  );
}
